import "./globals.css";
import type { Metadata } from "next";
import { Footer } from "../../presentation/components/footer";
import { Source_Sans_3 } from "@next/font/google";
import { ThemeProvider } from "../../presentation/components/ui/ThemeProvider";
import { NavBarComp } from "@/presentation/components/ui/navbar/NavBar";
import { Locales } from "@/interfaces";
import { locales } from "@/middleware";

const sourceSansPro = Source_Sans_3({
  weight: ["200", "300", "400", "700", "900"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  const langs = locales.map((locale) => ({ locale }));

  return langs;
}

export default function RootLayout({
  params: { locale },
  children,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locales };
}>) {
  return (
    <html lang={locale}>
      <ThemeProvider>
        <body className={sourceSansPro.className}>
          <NavBarComp locale={locale}></NavBarComp>
          <div className="mt-16">{children}</div>
          <Footer></Footer>
        </body>
      </ThemeProvider>
    </html>
  );
}
