import "./globals.css";
import "photoswipe/style.css";

import type { Metadata } from "next";
import { Source_Sans_3 } from "@next/font/google";
import { ThemeProvider } from "../../presentation/components/theme-providers/darkMode";
import { Locales } from "@/infraestructure/interfaces";
import { locales } from "@/middleware";

const sourceSansPro = Source_Sans_3({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  const langs = locales.map((locale) => ({ locale }));

  return langs;
}

export default function RootLayout({
  params: { locale },
  children,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locales };
}>) {
  return (
    <html lang={locale}>
      <ThemeProvider>
        <body
          className={
            sourceSansPro.className +
            " bg-white dark:bg-slate-800 h-full min-h-screen"
          }>
          <script src="https://unpkg.com/wavesurfer.js"></script>
          <div className="h-full min-h-screen">{children}</div>
        </body>
      </ThemeProvider>
    </html>
  );
}
